name: Alpha Environment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Notify Slack
      if: success()
      id: slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: C01D16VJ84C
        status: BUILD STARTED
        color: warning

    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache dependencies
      id: node-cache
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: alpha-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Build
      run: npm run build
      env:
        CI: false
        SKIP_PREFLIGHT_CHECK: true
        REACT_APP_ENV: 'production'
        REACT_APP_HTML_TITLE: 'BarnBridge'

        REACT_APP_WEB3_CHAIN_ID: 1
        REACT_APP_WEB3_POLLING_INTERVAL: 12000
        REACT_APP_WEB3_RPC_WSS_URL: 'wss://mainnet.infura.io/ws/v3/25763b5ba15644a8b3079d3ee755bce5'
        REACT_APP_WEB3_RPC_HTTPS_URL: 'https://mainnet.infura.io/v3/25763b5ba15644a8b3079d3ee755bce5'
        REACT_APP_WEB3_PORTIS_APP_ID: 'b0b0f776-bbf6-458c-a175-6483e0c452b7'
        REACT_APP_WEB3_WALLET_CONNECT_BRIDGE: 'https://bridge.walletconnect.org'
        REACT_APP_WEB3_COINBASE_APP_NAME: 'BarnBridge'
        REACT_APP_WEB3_TREZOR_EMAIL: 'bogdan@barnbridge.com'
        REACT_APP_WEB3_TREZOR_APP_URL: 'https://app.barnbridge.com/'
        REACT_APP_ETHERSCAN_API_KEY: '4RSJUUZQFMXUAUUJP5FI5UR5U59N7UIA32'

        REACT_APP_TOKEN_USDC_ADDR: ''
        REACT_APP_TOKEN_USDC_PRICE_ADDR: '0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6'

        REACT_APP_TOKEN_XYZ_ADDR: ''
        REACT_APP_TOKEN_XYZ_PRICE_ADDR: '0x86dEddCFc3a7DBeE68cDADA65Eed3D3b70F4fe24'

        REACT_APP_TOKEN_BOND_ADDR: ''
        REACT_APP_TOKEN_BOND_PRICE_ADDR: '0x6591c4BcD6D7A1eb4E537DA8B78676C1576Ba244'

        REACT_APP_TOKEN_AAVE_ADDR: ''
        REACT_APP_TOKEN_AAVE_PRICE_ADDR: '0x547a514d5e3769680Ce22B2361c10Ea13619e8a9'

        REACT_APP_TOKEN_COMP_ADDR: ''
        REACT_APP_TOKEN_COMP_PRICE_ADDR: '0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5'

        REACT_APP_TOKEN_SNX_ADDR: ''
        REACT_APP_TOKEN_SNX_PRICE_ADDR: '0xDC3EA94CD0AC27d9A86C180091e7f78C683d3699'

        REACT_APP_TOKEN_SUSHI_ADDR: ''
        REACT_APP_TOKEN_SUSHI_PRICE_ADDR: '0xe572CeF69f43c2E488b33924AF04BDacE19079cf'

        REACT_APP_TOKEN_LINK_ADDR: ''
        REACT_APP_TOKEN_LINK_PRICE_ADDR: '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c'

        REACT_APP_TOKEN_ILV_ADDR: '0x449ae80a139e724dd2506b8b312e898bf713fea9'

        REACT_APP_TOKEN_USDC_XYZ_SUSHI_LP_ADDR: ''
        REACT_APP_TOKEN_USDC_XYZ_SUSHI_LP_PRICE_ADDR: '0xe0dddd62431f705325f8d1e0474a31589622f54a'

        REACT_APP_CONTRACT_YF_STAKING_ADDR: ''
        REACT_APP_CONTRACT_YF_BOND_ADDR: ''
        REACT_APP_CONTRACT_YF_AAVE_ADDR: ''
        REACT_APP_CONTRACT_YF_COMP_ADDR: ''
        REACT_APP_CONTRACT_YF_SNX_ADDR: ''
        REACT_APP_CONTRACT_YF_SUSHI_ADDR: ''
        REACT_APP_CONTRACT_YF_LINK_ADDR: ''
        REACT_APP_CONTRACT_YF_ILV_ADDR: ''
        REACT_APP_CONTRACT_YF_USDC_XYZ_SUSHI_LP_ADDR: ''

        REACT_APP_BASE_API_URL: ''

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: build

    - name: Notify Slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel_id: C01D16VJ84C
        status: BUILD SUCCESSFUL
        color: good

    - name: Notify Slack failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel_id: C01D16VJ84C
        status: BUILD FAILED
        color: danger

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Notify Slack
      if: success()
      id: slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: C01D16VJ84C
        status: DEPLOYMENT STARTED
        color: warning

    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: frontend

    - name: Configure AWS credetials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3
      run: ls -l && aws s3 sync . s3://alpha-alphaappbarnbridgecom-origin --delete

    - name: Invalidate CloudFront cache
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        CF_DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items!=null] | [?contains(Aliases.Items, 'alpha.app.barnbridge.com')].Id | [0]" | tr -d \")
        echo "Clearing cache for ${CF_DIST_ID}..."
        CF_INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id ${CF_DIST_ID} --paths "/*" | jq -r '.Invalidation.Id')
        while [ $(aws cloudfront get-invalidation --distribution-id ${CF_DIST_ID} --id ${CF_INVALIDATION_ID} | jq -r '.Invalidation.Status') != "Completed" ]; do
          echo "CF_DIST_ID=${CF_DIST_ID} CF_INVALIDATION_ID=${CF_INVALIDATION_ID}: Waiting for CloudFront cache invalidation to complete..."
          sleep 5
        done

    - name: Notify Slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel_id: C01D16VJ84C
        status: DEPLOYMENT SUCCESSFUL
        color: good

    - name: Notify Slack failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel_id: C01D16VJ84C
        status: DEPLOYMENT FAILED
        color: danger
