name: Development Environment

on:
  push:
    branches:
    - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Notify Slack
      if: success()
      id: slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: infra-ci-kekdao
        status: BUILD STARTED
        color: warning

    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache dependencies
      id: node-cache
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Build
      run: npm run build
      env:
        CI: false
        HTTPS: true
        GENERATE_SOURCEMAP: false
        SKIP_PREFLIGHT_CHECK: true
        REACT_APP_ENV: 'development'
        REACT_APP_HTML_TITLE: 'Universe Rinkeby'
        REACT_APP_WEB3_CHAIN_ID: 4
        REACT_APP_WEB3_POLLING_INTERVAL: 12000
        REACT_APP_WEB3_RPC_WSS_URL: 'wss://rinkeby.infura.io/ws/v3/25763b5ba15644a8b3079d3ee755bce5'
        REACT_APP_WEB3_RPC_HTTPS_URL: 'https://rinkeby.infura.io/v3/25763b5ba15644a8b3079d3ee755bce5'
        REACT_APP_WEB3_PORTIS_APP_ID: '88597a67-b066-4b66-ad9b-e9262d8716f6'
        REACT_APP_WEB3_WALLET_CONNECT_BRIDGE: 'https://bridge.walletconnect.org'
        REACT_APP_WEB3_COINBASE_APP_NAME: 'universe.xyz'
        REACT_APP_WEB3_TREZOR_EMAIL: 'cezar@universe.xyz'
        REACT_APP_WEB3_TREZOR_APP_URL: 'https://universe.xyz/'
        REACT_APP_ETHERSCAN_API_KEY: '4RSJUUZQFMXUAUUJP5FI5UR5U59N7UIA32'
        REACT_APP_TOKEN_XYZ_ADDR: '0x41E88dc0dfA5455E64327484F1862332413520da'
        REACT_APP_TOKEN_USDC_ADDR: '0x1F719D2Ea53b9F7ee4dBFE51B0D91e892A05AA26'
        REACT_APP_TOKEN_BOND_ADDR: '0xdf695cf3118d504c33415cbc465dd469b7e4c881'
        REACT_APP_TOKEN_AAVE_ADDR: '0x7bdf7a5ab7a18985d1b1cb09b69338ba0c78f416'
        REACT_APP_TOKEN_COMP_ADDR: '0xfdf1a271f12148e11254dd63178ee1fbb8b4c75e'
        REACT_APP_TOKEN_SNX_ADDR: '0xff85fe0a2e8d66b9101305ab1522a37e0a50c4ef'
        REACT_APP_TOKEN_SUSHI_ADDR: '0xf3461cd59e3a3c25fd5f4c471df724a74cec4eeb'
        REACT_APP_TOKEN_LINK_ADDR: '0x2b9781477b64e48a263854B778d548Fc9560CbB5'
        REACT_APP_TOKEN_ILV_ADDR: '0x449ae80a139e724dd2506b8b312e898bf713fea9'
        REACT_APP_TOKEN_USDC_XYZ_SLP_ADDR: '0xaf8e2763b8e926b4e88715c4f45ccb20b6233f0b'
        REACT_APP_CONTRACT_YF_STAKING_ADDR: '0xe935190f2E28aF9FFb17BA7A5D494421a4a8c0fc'
        REACT_APP_CONTRACT_YF_BOND_ADDR: '0xAa496984F298bb4C31724672b5e8E0C69C716B11'
        REACT_APP_CONTRACT_YF_AAVE_ADDR: '0xED92703A7860cf9A52392800246a0e6Ac3811515'
        REACT_APP_CONTRACT_YF_COMP_ADDR: '0xc7Db7C109E7676e6D71CCf57827A880fe3A469d6'
        REACT_APP_CONTRACT_YF_SNX_ADDR: '0x6395049f4b6b807c94d9EdC9Ebb72c66D668D18A'
        REACT_APP_CONTRACT_YF_SUSHI_ADDR: '0x865a04afE1b56D137d398229D9358f8E29D31D41'
        REACT_APP_CONTRACT_YF_LINK_ADDR: '0x1303c0FCa3bAf7547dCd0168aE2e2ae7ba04D38A'
        REACT_APP_CONTRACT_YF_ILV_ADDR: '0x3f1A2ab9C216C729b215EB780a84CCdaA449889D'
        REACT_APP_CONTRACT_YF_USDC_XYZ_SLP_ADDR: '0x2E768c1c0436B0fb79536368957D08185dCCEB23'
        REACT_APP_CONTRACT_DAO_GOVERNANCE_ADDR: '0x63172A077b3740Dd9Ae311F81c72Edb7170F135c'
        REACT_APP_CONTRACT_DAO_BARN_ADDR: '0xb71fF62AEDFDCc68B72bEd3218c3cA137Dab0403'
        REACT_APP_CONTRACT_DAO_REWARD_ADDR: '0x7edAdA68A7FF81452De0D9cCfe8E8305B17Aa563'
        REACT_APP_DAO_ACTIVATION_THRESHOLD: 50000000
        REACT_APP_BASE_API_URL: 'https://dev.api.dao.universe.xyz'
    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: build

    - name: Notify Slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: infra-ci-kekdao
        status: BUILD SUCCESSFUL
        color: good

    - name: Notify Slack failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: infra-ci-kekdao
        status: BUILD FAILED
        color: danger

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Notify Slack
      if: success()
      id: slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: infra-ci-kekdao
        status: DEPLOYMENT STARTED
        color: warning

    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: frontend

    - name: Configure AWS credetials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3
      run: ls -l && aws s3 sync . s3://dev-devdaouniversexyz-origin --delete

    - name: Invalidate CloudFront cache
      run: |
        #!/usr/bin/env bash
        set -eou pipefail

        CF_DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items!=null] | [?contains(Aliases.Items, 'dev.dao.universe.xyz')].Id | [0]" | tr -d \")
        echo "Clearing cache for ${CF_DIST_ID}..."
        CF_INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id ${CF_DIST_ID} --paths "/*" | jq -r '.Invalidation.Id')
        while [ $(aws cloudfront get-invalidation --distribution-id ${CF_DIST_ID} --id ${CF_INVALIDATION_ID} | jq -r '.Invalidation.Status') != "Completed" ]; do
          echo "CF_DIST_ID=${CF_DIST_ID} CF_INVALIDATION_ID=${CF_INVALIDATION_ID}: Waiting for CloudFront cache invalidation to complete..."
          sleep 5
        done

    - name: Notify Slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: infra-ci-kekdao
        status: DEPLOYMENT SUCCESSFUL
        color: good

    - name: Notify Slack failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: infra-ci-kekdao
        status: DEPLOYMENT FAILED
        color: danger
