name: Development Environment

on:
  push:
    branches:
    - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Notify Slack
      if: success()
      id: slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: infra-ci-kekdao
        status: BUILD STARTED
        color: warning

    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache dependencies
      id: node-cache
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Build
      run: npm run build
      env:
        CI: false
        HTTPS: true
        GENERATE_SOURCEMAP: false
        SKIP_PREFLIGHT_CHECK: true
        REACT_APP_ENV: 'development'
        REACT_APP_HTML_TITLE: 'Universe Rinkeby'
        REACT_APP_WEB3_CHAIN_ID: 4
        REACT_APP_WEB3_POLLING_INTERVAL: 12000
        REACT_APP_WEB3_RPC_WSS_URL: 'wss://rinkeby.infura.io/ws/v3/25763b5ba15644a8b3079d3ee755bce5'
        REACT_APP_WEB3_RPC_HTTPS_URL: 'https://rinkeby.infura.io/v3/25763b5ba15644a8b3079d3ee755bce5'
        REACT_APP_WEB3_PORTIS_APP_ID: 'b0b0f776-bbf6-458c-a175-6483e0c452b7'
        REACT_APP_WEB3_WALLET_CONNECT_BRIDGE: 'https://bridge.walletconnect.org'
        REACT_APP_WEB3_COINBASE_APP_NAME: 'barnbridge'
        REACT_APP_WEB3_TREZOR_EMAIL: 'bogdan@barnbridge.com'
        REACT_APP_WEB3_TREZOR_APP_URL: 'https://app.barnbridge.com/'
        REACT_APP_ETHERSCAN_API_KEY: '4RSJUUZQFMXUAUUJP5FI5UR5U59N7UIA32'
        REACT_APP_TOKEN_XYZ_ADDR: '0x86dEddCFc3a7DBeE68cDADA65Eed3D3b70F4fe24'
        REACT_APP_TOKEN_USDC_ADDR: '0x86dEddCFc3a7DBeE68cDADA65Eed3D3b70F4fe24'
        REACT_APP_TOKEN_BOND_ADDR: '0xdf695cf3118d504c33415cbc465dd469b7e4c881'
        REACT_APP_TOKEN_AAVE_ADDR: '0x7bdf7a5ab7a18985d1b1cb09b69338ba0c78f416'
        REACT_APP_TOKEN_COMP_ADDR: '0xfdf1a271f12148e11254dd63178ee1fbb8b4c75e'
        REACT_APP_TOKEN_SNX_ADDR: '0xff85fe0a2e8d66b9101305ab1522a37e0a50c4ef'
        REACT_APP_TOKEN_SUSHI_ADDR: '0xf3461cd59e3a3c25fd5f4c471df724a74cec4eeb'
        REACT_APP_TOKEN_LINK_ADDR: '0x2b9781477b64e48a263854B778d548Fc9560CbB5'
        REACT_APP_TOKEN_ILV_ADDR: '0x449ae80a139e724dd2506b8b312e898bf713fea9'
        REACT_APP_TOKEN_USDC_XYZ_SUSHI_LP_ADDR: '0xfade438388f1fc3b1030c58bafdc91bfad162d4f'
        REACT_APP_CONTRACT_YF_STAKING_ADDR: '0x831B60137F2f9F37846BEB61C8E0913eb4BeC41b'
        REACT_APP_CONTRACT_YF_BOND_ADDR: '0x499be2068bA322070F89BFaCc16C680316DEB7c9'
        REACT_APP_CONTRACT_YF_AAVE_ADDR: '0x1aE898e43B89A50D8C51C3Bac204712f1B2B0dC7'
        REACT_APP_CONTRACT_YF_COMP_ADDR: '0xb4CD35018e1BC3C0A0aE4bC7bB1BB32D9B377d5D'
        REACT_APP_CONTRACT_YF_SNX_ADDR: '0xBF3384eDF7ac64B2EB413570F51D3E0fF8434e06'
        REACT_APP_CONTRACT_YF_SUSHI_ADDR: '0x4a5F0969bA2B87015F5485f9b6dDb353243445aA'
        REACT_APP_CONTRACT_YF_LINK_ADDR: '0x90cb1f39390B655b6e0f3312FafC41eCe039E619'
        REACT_APP_CONTRACT_YF_ILV_ADDR: '0x203f9fBaf49DDe4453C11a40aFd40Cd31E99aA72'
        REACT_APP_CONTRACT_YF_USDC_XYZ_SUSHI_LP_ADDR: '0xd318588f3a7D0d86E5e2A1917D54e0CF93D5d1d1'
        REACT_APP_CONTRACT_DAO_GOVERNANCE_ADDR: '0x52eea6822627819416531D4C0B221AE52652938a'
        REACT_APP_CONTRACT_DAO_BARN_ADDR: '0xFa7f183d5DDe994a908CA1969c50AE7538b60D8d'
        REACT_APP_CONTRACT_DAO_REWARD_ADDR: '0x0D9d63fad7d25D6daA749cb57149f47c7800A975'
        REACT_APP_BASE_API_URL: 'https://dev.api.dao.universe.xyz'
    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: build

    - name: Notify Slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: infra-ci-kekdao
        status: BUILD SUCCESSFUL
        color: good

    - name: Notify Slack failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: infra-ci-kekdao
        status: BUILD FAILED
        color: danger

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Notify Slack
      if: success()
      id: slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: infra-ci-kekdao
        status: DEPLOYMENT STARTED
        color: warning

    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: frontend

    - name: Configure AWS credetials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3
      run: ls -l && aws s3 sync . s3://dev-devdaouniversexyz-origin --delete

    - name: Invalidate CloudFront cache
      run: |
        #!/usr/bin/env bash
        set -eou pipefail

        CF_DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items!=null] | [?contains(Aliases.Items, 'dev.dao.universe.xyz')].Id | [0]" | tr -d \")
        echo "Clearing cache for ${CF_DIST_ID}..."
        CF_INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id ${CF_DIST_ID} --paths "/*" | jq -r '.Invalidation.Id')
        while [ $(aws cloudfront get-invalidation --distribution-id ${CF_DIST_ID} --id ${CF_INVALIDATION_ID} | jq -r '.Invalidation.Status') != "Completed" ]; do
          echo "CF_DIST_ID=${CF_DIST_ID} CF_INVALIDATION_ID=${CF_INVALIDATION_ID}: Waiting for CloudFront cache invalidation to complete..."
          sleep 5
        done

    - name: Notify Slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: infra-ci-kekdao
        status: DEPLOYMENT SUCCESSFUL
        color: good

    - name: Notify Slack failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: infra-ci-kekdao
        status: DEPLOYMENT FAILED
        color: danger
